version: '2'

services:
  nginx: 
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80   
      - 443:443
    restart: unless-stopped  

  rabbitmq:
    container_name: rabbitmq
    #image: introproventures/activiti-rabbitmq:3.7-alpine
    #image: rabbitmq:3.7-alpine
    image: activiti/rabbitmq-stomp:7.0.0.RC1
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
     - rabbitmq-data
    restart: unless-stopped

  keycloak:
    container_name: keycloak
    image: activiti/activiti-keycloak
    ports:
      - 8180:8180
    restart: unless-stopped
  example-runtime-bundle:
    container_name: example-runtime-bundle
    image: activiti/example-runtime-bundle:7.0.0.GA
    #build: ./media-eng-rb
    ports:
      - 8080:8080
    #   - 8000:8000
    environment:
      # JAVA_OPTS: "-Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8000,suspend=n -noverify"
      SPRING_JMX_ENABLED: "false"
      ACT_KEYCLOAK_URL: "http://192.168.1.9.nip.io/auth"
      SPRING_RABBITMQ_HOST: "rabbitmq"
    restart: unless-stopped
  example-cloud-connector:
    container_name: example-cloud-connector
    image: activiti/example-cloud-connector:7.0.0.GA
    ports:
      - 8081:8080
    #   - 8000:8000
    environment:
      # JAVA_OPTS: "-Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8000,suspend=n -noverify"
      SPRING_JMX_ENABLED: "false"
      SPRING_RABBITMQ_HOST: "rabbitmq"
      ACT_KEYCLOAK_URL: "http://192.168.1.9.nip.io/auth"
    restart: unless-stopped

  activiti-cloud-query:
    container_name: activiti-cloud-query
    image: activiti/activiti-cloud-query:7.0.0.GA
    ports:
      - 8082:8080
    environment:
      # JAVA_OPTS: "-Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8000,suspend=n -noverify"
      SPRING_JMX_ENABLED: "false"
      SPRING_RABBITMQ_HOST: "rabbitmq"
      ACT_KEYCLOAK_URL: "http://192.168.1.9.nip.io/auth"
    restart: unless-stopped      
  
  activiti-cloud-audit:
    container_name: activiti-cloud-audit
    image: activiti/activiti-cloud-audit:7.0.0.GA
    ports:
      - 8083:8080
    environment:
      # JA`VA_OPTS: "-Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8000,suspend=n -noverify"
      SPRING_JMX_ENABLED: "false"
      SPRING_RABBITMQ_HOST: "rabbitmq"
      ACT_KEYCLOAK_URL: "http://192.168.1.9.nip.io/auth"
    restart: unless-stopped      

  activiti-cloud-notifications-graphql:  
    container_name: activiti-cloud-notifications-graphql
    image: activiti/activiti-cloud-notifications-graphql:7.0.0.GA
    ports:
      - 8084:8080
    environment:
      # JAVA_OPTS: "-Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8000,suspend=n -noverify"
      SPRING_JMX_ENABLED: "false"
      SPRING_RABBITMQ_HOST: "rabbitmq"
      ACT_KEYCLOAK_URL: "http://192.168.1.9.nip.io/auth"
    restart: unless-stopped
  
  activiti-modeling-app:
    container_name: activiti-modeling-app
    image: activiti/activiti-modeling-app:0.0.35
    ports:
      - 8085:80
    environment:
      # JAVA_OPTS: "-Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8000,suspend=n -noverify"
      APP_CONFIG_OAUTH2_HOST: "http://192.168.1.9.nip.io/auth/realms/activiti"
      APP_CONFIG_OAUTH2_CLIENTID: "activiti"
      APP_CONFIG_BPM_HOST: "http://192.168.1.9.nip.io"
      BASE_PATH:                                     /activiti-cloud-modeling/
      APP_CONFIG_OAUTH2_REDIRECT_SILENT_IFRAME_URI:  /activiti-cloud-modeling/assets/silent-refresh.html
      APP_CONFIG_OAUTH2_REDIRECT_LOGIN:              /activiti-cloud-modeling
      APP_CONFIG_OAUTH2_REDIRECT_LOGOUT:             /activiti-cloud-modeling
      API_PATH_PREFIX:                               activiti-cloud-modeling-backend
    restart: unless-stopped

  activiti-cloud-modeling-backend:
    container_name: activiti-cloud-modeling-backend
    image: activiti/activiti-cloud-modeling:7.1.69
    environment:
      JAVA_OPTS:                    -Xmx1024m -Xms512m -XX:+UnlockExperimentalVMOptions   -Dsun.zip.disableMemoryMapping=true -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90
      SPRING_APPLICATION_NAME:      activiti-cloud-modeling-backend
      SERVER_PORT:                  8080
      ACT_KEYCLOAK_URL:             http://192.168.1.9.nip.io/auth
      ACTIVITI_CLOUD_MODELING_URL:  localhost:8080

volumes:
  rabbitmq-data:

    
